name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '9'

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Update patch dependencies
        run: |
          pnpm update --latest --filter="./src/**"
          pnpm update --latest --filter="./tests/**"

      - name: Run tests after update
        run: |
          pnpm run check
          pnpm run lint
          pnpm run test
        continue-on-error: true

      - name: Check for changes
        id: changes
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: automated dependency updates'
          body: |
            ## Automated Dependency Updates
            
            This PR contains automated dependency updates generated by GitHub Actions.
            
            ### Changes Made
            - Updated patch versions of dependencies
            - Refreshed lockfile
            
            ### Verification
            - [ ] All tests are passing
            - [ ] No breaking changes detected
            - [ ] Security audit clean
            
            ### Next Steps
            Please review the changes and merge if everything looks good.
            
            ---
            🤖 This PR was generated automatically by GitHub Actions
          branch: chore/dependency-updates
          delete-branch: true

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run security audit
        run: pnpm audit --audit-level moderate

      - name: Run vulnerability scan
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate

  outdated-check:
    name: Check Outdated Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check for outdated dependencies
        id: outdated
        run: |
          echo "outdated-packages<<EOF" >> $GITHUB_OUTPUT
          pnpm outdated --format list >> $GITHUB_OUTPUT || true
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create issue for major updates
        if: steps.outdated.outputs.outdated-packages != ''
        uses: actions/github-script@v7
        with:
          script: |
            const outdated = `${{ steps.outdated.outputs.outdated-packages }}`;
            
            if (outdated.includes('major')) {
              github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: '🔧 Major dependency updates available',
                body: `## Major Dependency Updates Available
                
The following packages have major version updates available:

\`\`\`
${outdated}
\`\`\`

### Action Required
Please review these updates carefully as they may contain breaking changes.

### Steps to Update
1. Review the changelog for each package
2. Test the updates in a separate branch
3. Update the codebase if breaking changes are present
4. Create a PR with the updates

---
🤖 This issue was generated automatically by GitHub Actions`,
                labels: ['dependencies', 'maintenance', 'breaking-change']
              });
            }